// (c) Copyright HutongGames, LLC 2010-2023. All rights reserved.
// THIS CONTENT IS AUTOMATICALLY GENERATED. __PLAYMAKER_EVENT_PROXY__
// this script was generated by the 'PlayMaker Event Proxy Wizard'. You can edit this script directly now, but prefer using the wizard if you are not sure.

using UnityEngine;
using HutongGames.PlayMaker.Ecosystem.Utils;
using HutongGames.PlayMaker;

namespace com.spine
{
	public class EnemyReadyProxy : PlayMakerEventProxy {

		[Button("EnemyReady","Test : EnemyReady")] public bool _;
		public void EnemyReady()
		{
			if (debug || !Application.isPlaying)
			{
				Debug.Log("EnemyReadyProxy : EnemyReady()");
			}

            

			base.SendPlayMakerEvent();
		}
	}
}