// (c) Copyright HutongGames, LLC 2010-2022. All rights reserved.
// THIS CONTENT IS AUTOMATICALLY GENERATED. __PLAYMAKER_EVENT_PROXY__
// this script was generated by the 'PlayMaker Event Proxy Wizard'. You can edit this script directly now, but prefer using the wizard if you are not sure.

using UnityEngine;
using HutongGames.PlayMaker.Ecosystem.Utils;
using HutongGames.PlayMaker;

namespace com.laser
{
	public class LaserStartProxy : PlayMakerEventProxy {

		[Button("LaserStart","Test : LaserStart")] public bool _;
		public void LaserStart()
		{
			if (debug || !Application.isPlaying)
			{
				Debug.Log("LaserStartProxy : LaserStart()");
			}

            

			base.SendPlayMakerEvent();
		}
	}
}